/**
 * This file is autogenerated by Scaffold-ETH.
 * You should not edit it manually or your changes might be overwritten.
 */
import { GenericContractsDeclaration } from "~~/utils/scaffold-eth/contract";

const deployedContracts = {
  31337: {
    Config: {
      address: "0x4e6069b73a2d3a79ca27700b1d300d9e0d3d4bff",
      abi: [
        {
          type: "constructor",
          inputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "AUCTION_DURATION_TIME",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "BASIS_POINTS",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "CHARACTER_OWNER_TAX_BPS",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "CHARACTER_TOKEN_DECIMALS",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint8",
              internalType: "uint8",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "INITIAL_CHARACTER_TOKEN_SUPPLY",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "LP_LOCK_BPS",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "PROTOCOL_ADMIN_TAX_BPS",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "WETH",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "contract ERC20",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "auctionVault",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "contract AuctionVault",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "digicharFactory",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "contract DigicharFactory",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "ownershipCertificate",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "contract DigicharOwnershipCertificate",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "protocolAdmin",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "setAuctionDuration",
          inputs: [
            {
              name: "_auctionDuration",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "setAuctionVault",
          inputs: [
            {
              name: "_auctionVault",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "setCharacterOwnerTaxBps",
          inputs: [
            {
              name: "_CHARACTER_OWNER_TAX_BPS",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "setDigicharFactory",
          inputs: [
            {
              name: "_digicharFactory",
              type: "address",
              internalType: "address payable",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "setLpLockBps",
          inputs: [
            {
              name: "_LP_LOCK_BPS",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "setOwnershipCertificate",
          inputs: [
            {
              name: "_ownershipCertificate",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "setProtocolAdminTaxBps",
          inputs: [
            {
              name: "_PROTOCOL_ADMIN_TAX_BPS",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "setSwapFactory",
          inputs: [
            {
              name: "_swapFactory",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "setSwapRouter",
          inputs: [
            {
              name: "_swapRouter",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "setWETH",
          inputs: [
            {
              name: "_weth",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "swapFactory",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "contract IUniswapV2Factory",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "swapRouter",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "contract IUniswapV2Router02",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "updateProtocolAdmin",
          inputs: [
            {
              name: "_protocolAdmin",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "event",
          name: "AuctionDurationSet",
          inputs: [
            {
              name: "_protocolAdmin",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "_auctionDuration",
              type: "uint256",
              indexed: true,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "AuctionVaultSet",
          inputs: [
            {
              name: "_protocolAdmin",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "_auctionVault",
              type: "address",
              indexed: false,
              internalType: "address",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "CharacterOwnerTaxBpsSet",
          inputs: [
            {
              name: "_protocolAdmin",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "_CHARACTER_OWNER_TAX_BPS",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "DigicharFactorySet",
          inputs: [
            {
              name: "_protocolAdmin",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "_digicharFactory",
              type: "address",
              indexed: false,
              internalType: "address",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "LpLockBpsSet",
          inputs: [
            {
              name: "_protocolAdmin",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "_LP_LOCK_BPS",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "OwnershipCertificateSet",
          inputs: [
            {
              name: "_protocolAdmin",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "_ownershipCertificate",
              type: "address",
              indexed: false,
              internalType: "address",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "ProtocolAdminTaxBpsSet",
          inputs: [
            {
              name: "_protocolAdmin",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "_PROTOCOL_ADMIN_TAX_BPS",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "ProtocolAdminUpdated",
          inputs: [
            {
              name: "_protocolAdmin",
              type: "address",
              indexed: false,
              internalType: "address",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "SwapFactorySet",
          inputs: [
            {
              name: "_protocolAdmin",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "indexed_swapRouter",
              type: "address",
              indexed: false,
              internalType: "address",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "SwapRouterSet",
          inputs: [
            {
              name: "_protocolAdmin",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "indexed_swapRouter",
              type: "address",
              indexed: false,
              internalType: "address",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "WethSet",
          inputs: [
            {
              name: "_weth",
              type: "address",
              indexed: false,
              internalType: "address",
            },
          ],
          anonymous: false,
        },
        {
          type: "error",
          name: "OnlyProtocolAdmin",
          inputs: [],
        },
      ],
      inheritedFunctions: {},
      deploymentFile: "run-1750067058.json",
      deploymentScript: "Deploy.s.sol",
    },
    AuctionVault: {
      address: "0xa0e9538cfdb2f3c84dd2df0c3f0ff2a46a9b16b8",
      abi: [
        {
          type: "constructor",
          inputs: [
            {
              name: "_config",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "auctionId",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "auctions",
          inputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "endTime",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "bid",
          inputs: [
            {
              name: "_characterIndex",
              type: "uint8",
              internalType: "uint8",
            },
          ],
          outputs: [],
          stateMutability: "payable",
        },
        {
          type: "function",
          name: "checkUnclaimedTokens",
          inputs: [
            {
              name: "_user",
              type: "address",
              internalType: "address",
            },
            {
              name: "_auctionId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "claimTokens",
          inputs: [
            {
              name: "_auctionId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "closeCurrentAuction",
          inputs: [
            {
              name: "_topBidder",
              type: "address",
              internalType: "address",
            },
            {
              name: "_winningCharacterIndex",
              type: "uint8",
              internalType: "uint8",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "createAuction",
          inputs: [
            {
              name: "characterURIs",
              type: "string[3]",
              internalType: "string[3]",
            },
            {
              name: "names",
              type: "string[3]",
              internalType: "string[3]",
            },
            {
              name: "symbols",
              type: "string[3]",
              internalType: "string[3]",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "getAuctionCharacterData",
          inputs: [
            {
              name: "_auctionId",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "_characterIndex",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "string",
              internalType: "string",
            },
            {
              name: "",
              type: "string",
              internalType: "string",
            },
            {
              name: "",
              type: "string",
              internalType: "string",
            },
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getCharacterTokenAddress",
          inputs: [
            {
              name: "_auctionId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getCurrentAuctionEndTime",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getPoolBalance",
          inputs: [
            {
              name: "_auctionId",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "_characterIndex",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getUserBidBalance",
          inputs: [
            {
              name: "_user",
              type: "address",
              internalType: "address",
            },
            {
              name: "_auctionId",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "_characterIndex",
              type: "uint8",
              internalType: "uint8",
            },
          ],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "userBidBalance",
          inputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "",
              type: "uint8",
              internalType: "uint8",
            },
          ],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "withdrawBid",
          inputs: [
            {
              name: "_auctionId",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "_characterIndex",
              type: "uint8",
              internalType: "uint8",
            },
            {
              name: "_amount",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "event",
          name: "AuctionTimeChanged",
          inputs: [
            {
              name: "_auctionDurationTime",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "BidPlaced",
          inputs: [
            {
              name: "_auctionId",
              type: "uint256",
              indexed: true,
              internalType: "uint256",
            },
            {
              name: "_user",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "_amount",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
            {
              name: "_characterId",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "BidWithdrawn",
          inputs: [
            {
              name: "_auctionId",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
            {
              name: "user",
              type: "address",
              indexed: false,
              internalType: "address",
            },
            {
              name: "_withdrawAmount",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "DigicharTokenSet",
          inputs: [
            {
              name: "_digicharToken",
              type: "address",
              indexed: false,
              internalType: "address",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "TokensClaimed",
          inputs: [
            {
              name: "_user",
              type: "address",
              indexed: false,
              internalType: "address",
            },
            {
              name: "_auctionId",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "error",
          name: "AlreadyClaimed",
          inputs: [],
        },
        {
          type: "error",
          name: "AmountTooLarge",
          inputs: [],
        },
        {
          type: "error",
          name: "AmountZero",
          inputs: [],
        },
        {
          type: "error",
          name: "AuctionClosed",
          inputs: [],
        },
        {
          type: "error",
          name: "AuctionExpired",
          inputs: [],
        },
        {
          type: "error",
          name: "AuctionStillOpen",
          inputs: [],
        },
        {
          type: "error",
          name: "InvalidCharacter",
          inputs: [],
        },
        {
          type: "error",
          name: "OnlyProtocolAdmin",
          inputs: [],
        },
      ],
      inheritedFunctions: {},
      deploymentFile: "run-1750067058.json",
      deploymentScript: "Deploy.s.sol",
    },
    DigicharFactory: {
      address: "0xaeb5b4df3a478fd464f851fcd9022ec65e0d715b",
      abi: [
        {
          type: "constructor",
          inputs: [
            {
              name: "_config",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "receive",
          stateMutability: "payable",
        },
        {
          type: "function",
          name: "createCharacter",
          inputs: [
            {
              name: "_winningBidder",
              type: "address",
              internalType: "address",
            },
            {
              name: "_winningCharacterIndex",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "_characterTokenURI",
              type: "string",
              internalType: "string",
            },
            {
              name: "_characterName",
              type: "string",
              internalType: "string",
            },
            {
              name: "_characterSymbol",
              type: "string",
              internalType: "string",
            },
          ],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "payable",
        },
        {
          type: "event",
          name: "LPInitialized",
          inputs: [
            {
              name: "_token",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "_pair",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "_amountToken",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
            {
              name: "_amountEth",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
            {
              name: "_liquidity",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "PairCreated",
          inputs: [
            {
              name: "_token",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "_pair",
              type: "address",
              indexed: true,
              internalType: "address",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "Received",
          inputs: [
            {
              name: "",
              type: "address",
              indexed: false,
              internalType: "address",
            },
            {
              name: "",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "SwapFactorySet",
          inputs: [
            {
              name: "_swapFactory",
              type: "address",
              indexed: true,
              internalType: "address",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "TokenCreated",
          inputs: [
            {
              name: "_token",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "_name",
              type: "string",
              indexed: false,
              internalType: "string",
            },
            {
              name: "_symbol",
              type: "string",
              indexed: false,
              internalType: "string",
            },
          ],
          anonymous: false,
        },
        {
          type: "error",
          name: "InsufficientBalance",
          inputs: [],
        },
        {
          type: "error",
          name: "OnlyAuctionVault",
          inputs: [],
        },
        {
          type: "error",
          name: "OnlyProtocolAdmin",
          inputs: [],
        },
      ],
      inheritedFunctions: {},
      deploymentFile: "run-1750067058.json",
      deploymentScript: "Deploy.s.sol",
    },
    DigicharOwnershipCertificate: {
      address: "0x6635eb0e44cdd7d6dd81236ba1f1054666066537",
      abi: [
        {
          type: "constructor",
          inputs: [
            {
              name: "_digicharFactory",
              type: "address",
              internalType: "address payable",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "approve",
          inputs: [
            {
              name: "spender",
              type: "address",
              internalType: "address",
            },
            {
              name: "id",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "balanceOf",
          inputs: [
            {
              name: "owner",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "digicharFactory",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "contract DigicharFactory",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getApproved",
          inputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "isApprovedForAll",
          inputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "mint",
          inputs: [
            {
              name: "_to",
              type: "address",
              internalType: "address",
            },
            {
              name: "_tokenURI",
              type: "string",
              internalType: "string",
            },
          ],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "name",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "string",
              internalType: "string",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "ownerOf",
          inputs: [
            {
              name: "id",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "owner",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "safeTransferFrom",
          inputs: [
            {
              name: "from",
              type: "address",
              internalType: "address",
            },
            {
              name: "to",
              type: "address",
              internalType: "address",
            },
            {
              name: "id",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "safeTransferFrom",
          inputs: [
            {
              name: "from",
              type: "address",
              internalType: "address",
            },
            {
              name: "to",
              type: "address",
              internalType: "address",
            },
            {
              name: "id",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "data",
              type: "bytes",
              internalType: "bytes",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "setApprovalForAll",
          inputs: [
            {
              name: "operator",
              type: "address",
              internalType: "address",
            },
            {
              name: "approved",
              type: "bool",
              internalType: "bool",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "supportsInterface",
          inputs: [
            {
              name: "interfaceId",
              type: "bytes4",
              internalType: "bytes4",
            },
          ],
          outputs: [
            {
              name: "",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "symbol",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "string",
              internalType: "string",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "tokenId",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "tokenURI",
          inputs: [
            {
              name: "id",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "string",
              internalType: "string",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "tokenURIs",
          inputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "string",
              internalType: "string",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "transferFrom",
          inputs: [
            {
              name: "from",
              type: "address",
              internalType: "address",
            },
            {
              name: "to",
              type: "address",
              internalType: "address",
            },
            {
              name: "id",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "event",
          name: "Approval",
          inputs: [
            {
              name: "owner",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "spender",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "id",
              type: "uint256",
              indexed: true,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "ApprovalForAll",
          inputs: [
            {
              name: "owner",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "operator",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "approved",
              type: "bool",
              indexed: false,
              internalType: "bool",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "OwnershipCertificateMinted",
          inputs: [
            {
              name: "_to",
              type: "address",
              indexed: false,
              internalType: "address",
            },
            {
              name: "_tokenId",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
            {
              name: "_tokenURI",
              type: "string",
              indexed: false,
              internalType: "string",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "Transfer",
          inputs: [
            {
              name: "from",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "to",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "id",
              type: "uint256",
              indexed: true,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "error",
          name: "OnlyDigicharFactory",
          inputs: [],
        },
      ],
      inheritedFunctions: {},
      deploymentFile: "run-1750067058.json",
      deploymentScript: "Deploy.s.sol",
    },
  },
} as const;

export default deployedContracts satisfies GenericContractsDeclaration;
